language: julia
dist: trusty
sudo: true
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
env:
  - DOCUMENTER_DEBUG="true" CONDA_JL_VERSION="2" PYTHON=""
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
